container:
  image: openjdk:11-jdk
  cpu: 2
  memory: 1G

script:
  - java -version
  - git clone https://github.com/watchdog-wms/build-tools
  - WATCHDOG_PR_CHECKER=$(pwd)/build-tools/jars/PullRequestChecker.jar
  - ls "${WATCHDOG_PR_CHECKER}" > /dev/null 2>&1

task:
  name: signed commit test
  depends_on: install
  script: 
    - env
    - ls -la .
    - java -jar "${WATCHDOG_PR_CHECKER}" -check "VERIFIED_COMMIT"
