container:
  image: openjdk:11-jdk
  cpu: 2
  memory: 1G

task:
  name: install
  script:
  - git clone https://github.com/watchdog-wms/build-tools
  - WATCHDOG_PR_CHECKER=$(pwd)/build-tools/jars/PullRequestChecker.jar
  always: ls "${WATCHDOG_PR_CHECKER}" > /dev/null 2>&1

task:
  name: java test
  depends_on: install
  script: java -version

task:
  name: VERIFIED_COMMIT
  depends_on: install
  script: 
    - env
    - java -jar "${WATCHDOG_PR_CHECKER}" -check "VERIFIED_COMMIT"
