language: minimal
sudo: false 
dist: trusty
script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - COMMITER=$($TRAVIS_PULL_REQUEST_SLUG | sed 's#/.+##') && echo $COMMITER
  - CHANGED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE) && echo $CHANGED_FILES
  - false
name: "permission test"
